[package]
name = "foldertodmg"
version = "0.1.2"
authors = ["Samuel Marcaille"]
edition = "2018"
license = "MIT"
description = "foldertodmg is a personnal helper to create image from directory"
homepage = "https://github.com/deild/foldertodmg"
repository = "https://github.com/deild/foldertodmg"

[dependencies]

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["suggestions"]

[dev-dependencies]
assert_cmd = "1.0.2"
predicates = "1.0.5"