name: CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'macos-11.0', 'macos-10.15' ]
    steps:
      - uses: actions/checkout@v2
      - name: Info
        run: |
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V
          hdiutil info -s
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose