name: Release Tags
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  once:
    name: Create Release
    runs-on: macos-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEILD_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: Upload binaries on Release
    needs: once
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11.0
            link: macos-11
          - os: macos-10.15
            link: macos-10.15
    env:
      GITHUB_TOKEN: ${{ secrets.DEILD_TOKEN }}
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ matrix.link }}-${{ github.event.release.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release
      - name: Create Archive
        run: |
          tar -czvf ${ARCHIVE_NAME}.tar.gz -C $(pwd)/target/release -- ${{ github.event.repository.name }}
          shasum -a 256 ${ARCHIVE_NAME}.tar.gz > ${ARCHIVE_NAME}-sha256-checksum.txt
          cat ${ARCHIVE_NAME}-checksum.txt
      - name: Upload binary
        id: upload-binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_name: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_content_type: application/tar+gzip
      - name: Upload SHA256 Checksum
        id: upload-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEILD_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}-sha256-checksum.txt
          asset_name: ${{ env.ARCHIVE_NAME }}-sha256-checksum.txt
          asset_content_type: text/plain
